version: '2'

services:
  apache:
    build: 
      context: ./apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql